Terraform with GitHub Action

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -4,6 +4,10 @@ on:
   pull_request:
     branches:
       - main
+    paths:
+      - 'terraform/env/dev/**'
+      # - 'terraform/env/stg/**'
+      # - 'terraform/env/prod/**'
 
 permissions:
   id-token: write
@@ -13,8 +17,13 @@ jobs:
   terraform:
     strategy:
       matrix:
-        environment:
-          - dev
+        include:
+          - environment: dev
+            role: 'arn:aws:iam::351049001406:role/GithubActionRole'
+          # - environment: stg
+          #   role: 'arn:aws:iam::351049001406:role/GithubActionRole'
+          # - environment: prod
+          #   role: 'arn:aws:iam::351049001406:role/GithubActionRole'
 
     runs-on: ubuntu-latest
     steps:
@@ -22,9 +31,9 @@ jobs:
         uses: actions/checkout@v4
 
       - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v3
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::351049001406:role/GithubActionRole
+          role-to-assume: ${{ matrix.role }}
           aws-region: us-west-2
 
       - name: Set up Terraform
@@ -47,20 +56,8 @@ jobs:
         run: |
           cd terraform/env/${{ matrix.environment }}
           terraform plan -out=tfplan.binary
-        continue-on-error: true
-
-      - name: Convert plan to JSON
-        id: convert-plan
+      - name: Check for Terraform plan errors
+        if: failure()
         run: |
-          cd terraform/env/${{ matrix.environment }}
-          terraform show -json tfplan.binary > tfplan.json
-        continue-on-error: true
-
-      - name: Output Terraform plan as checks
-        id: output-checks
-        uses: EndBug/add-and-commit@v7
-        with:
-          default_author: github-actions[bot]
-          message: Add result of Terraform plan as checks for ${{ matrix.environment }}
-          add: |
-            terraform/env/${{ matrix.environment }}/tfplan.json
+          echo "Terraform plan failed"
+          exit 1
